### ISSUE TITLE
多开如何执行

### ISSUE THREAD

**Issue by yunbeyond** [Wrong-pixel/epic7auto#1]
怎么在多开的情况下执行有E7的模拟器命令

**Comment by Wrong-pixel** [comment]
> 怎么在多开的情况下执行有E7的模拟器命令

多开的情况下，脚本不能够直接使用exe了，因为多开需要解决adb的端口问题，但是脚本端口是写死的，具体解决办法可以参考以下：
1、参考https://www.bilibili.com/read/cv22109707，配置多开后的每个模拟器端口
2、使用sourceCode中的main.py运行脚本，每运行一个脚本前需要修改脚本中的adb连接端口

开发的时候没有考虑到多开需求，后续会在工具上添加一个adb连接信息的输入框，可以解决多开的需求

**Comment by yunbeyond** [comment]
好了，第二种改了一下adb端口就可以了，感谢

**Comment by Wrong-pixel** [comment]
> 好了，第二种改了一下adb端口就可以了，感谢

新版本已经更新adb地址的输入框，不用在源代码里面改了
