### ISSUE TITLE
循环只执行一次就被卡住

### ISSUE THREAD

**Issue by Taylor-Guo** [Wrong-pixel/epic7auto#3]
![image](https://github.com/Wrong-pixel/epic7auto/assets/78411439/b2670949-bd2a-43bc-a0e0-9ec9e069afe3)
![image](https://github.com/Wrong-pixel/epic7auto/assets/78411439/a8eb2f10-fa31-496c-bd6f-827d66ea1ab7)
请帮忙看看问题

**Comment by Taylor-Guo** [comment]
![image](https://github.com/Wrong-pixel/epic7auto/assets/78411439/879aeacd-e071-49e8-abe9-0b27955e4ae0)
补充一下模拟器adb接口

**Comment by Wrong-pixel** [comment]
> ![image](https://user-images.githubusercontent.com/78411439/258004509-b2670949-bd2a-43bc-a0e0-9ec9e069afe3.png) ![image](https://user-images.githubusercontent.com/78411439/258004557-a8eb2f10-fa31-496c-bd6f-827d66ea1ab7.png) 请帮忙看看问题

第一次循环能够正常进行下滑、点击刷新等操作吗？
